@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
@if(session('success')) <div class="alert alert-success border-0 shadow-sm"><i class="bi bi-check-circle me-2"></i>{{ session('success') }}</div> @endif
@if(session('error')) <div class="alert alert-danger border-0 shadow-sm">{{ session('error') }}</div> @endif

@if($user->role === 'peminjam')
  <div class="mb-4"><div class="eyebrow">Ruang peminjam</div><h2 class="fw-bold mb-1">Daftar Alat</h2><p class="text-muted mb-0">Pilih alat yang tersedia untuk kebutuhan Anda.</p></div>
  <div class="row g-3 mb-5">
    @forelse($alats as $alat)
    <div class="col-12 col-sm-6 col-xl-4"><div class="card h-100 p-3"><div class="d-flex gap-3"><div class="equipment-icon"><i class="bi bi-tools"></i></div><div class="flex-grow-1"><h6 class="fw-bold mb-1">{{ $alat->nama_alat }}</h6><small class="text-muted">{{ $alat->kategori->nama_kategori ?? 'Umum' }}</small></div></div><p class="small text-muted mt-3 mb-3">{{ $alat->deskripsi ?: 'Alat siap digunakan untuk mendukung aktivitas Anda.' }}</p><div class="d-flex justify-content-between align-items-center mt-auto"><span class="small"><strong>{{ $alat->stok }}</strong> stok tersedia</span><button class="btn btn-primary btn-sm px-3" data-bs-toggle="modal" data-bs-target="#pinjamModal" data-alat="{{ $alat->id }}" data-nama="{{ $alat->nama_alat }}" @disabled($alat->stok < 1 || $alat->status !== 'ada')>Pinjam <i class="bi bi-arrow-right ms-1"></i></button></div></div></div>
    @empty <div class="col-12"><div class="card p-5 text-center text-muted">Belum ada alat tersedia.</div></div> @endforelse
  </div>
  <div id="riwayat" class="d-flex justify-content-between align-items-center mb-3"><div><div class="eyebrow">Aktivitas Anda</div><h4 class="fw-bold mb-0">Riwayat Peminjaman</h4></div></div>
  <div class="card p-2 p-md-3"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Alat</th><th>Tanggal Pinjam</th><th>Rencana Kembali</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
  @forelse($riwayats as $riwayat)<tr><td class="fw-semibold">{{ $riwayat->alat->nama_alat ?? '-' }}</td><td>{{ \Carbon\Carbon::parse($riwayat->tgl_pinjam)->format('d M Y') }}</td><td>{{ \Carbon\Carbon::parse($riwayat->tgl_harap_kembali)->format('d M Y') }}</td><td><span class="badge rounded-pill text-bg-{{ $riwayat->status === 'disetujui' ? 'success' : ($riwayat->status === 'pending' ? 'warning' : 'secondary') }}">{{ ucfirst($riwayat->status) }}</span></td><td class="text-end">@if($riwayat->status === 'disetujui')<form method="POST" action="{{ route('peminjaman.pengembalian', $riwayat->id) }}">@csrf<button class="btn btn-outline-primary btn-sm">Kembalikan Alat</button></form>@else<span class="text-muted small">-</span>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada riwayat peminjaman.</td></tr>@endforelse
  </tbody></table></div></div>
  <div class="modal fade" id="pinjamModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 rounded-4"><form method="POST" action="{{ route('peminjaman.ajukan') }}">@csrf<div class="modal-header border-0"><div><div class="eyebrow">Form pengajuan</div><h5 class="modal-title fw-bold">Mengajukan Peminjaman</h5></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body pt-0"><input type="hidden" name="alat_id" id="alat_id"><div class="alert alert-primary py-2 small"><i class="bi bi-info-circle me-1"></i> Pengajuan akan diproses oleh petugas.</div><div class="mb-3"><label class="form-label">Alat</label><input id="alat_nama" class="form-control" readonly></div><div class="row g-3"><div class="col-6"><label class="form-label">Tanggal pinjam</label><input type="date" name="tgl_pinjam" class="form-control" min="{{ now()->format('Y-m-d') }}" required></div><div class="col-6"><label class="form-label">Tanggal kembali</label><input type="date" name="tgl_harap_kembali" class="form-control" min="{{ now()->format('Y-m-d') }}" required></div></div></div><div class="modal-footer border-0"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Ajukan Peminjaman</button></div></form></div></div></div>
  <script>document.getElementById('pinjamModal').addEventListener('show.bs.modal',e=>{const b=e.relatedTarget;document.getElementById('alat_id').value=b.dataset.alat;document.getElementById('alat_nama').value=b.dataset.nama;});</script>
@elseif($user->role === 'admin')
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="eyebrow">Administrasi</div><h2 class="fw-bold mb-1">Kelola Alat</h2><p class="text-muted mb-0">Kelola inventaris dan ketersediaan alat.</p></div><a href="{{ route('admin.alat.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Tambah Alat</a></div>
  <div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card p-3"><div class="eyebrow">Total user</div><h3 class="fw-bold mb-0">{{ $totalUser }}</h3><a href="{{ route('admin.users.index') }}" class="small text-decoration-none">Kelola user</a></div></div><div class="col-6 col-xl-3"><div class="card p-3"><div class="eyebrow">Kategori</div><h3 class="fw-bold mb-0">{{ $totalKategori }}</h3><a href="{{ route('admin.kategori.index') }}" class="small text-decoration-none">Kelola kategori</a></div></div><div class="col-6 col-xl-3"><div class="card p-3"><div class="eyebrow">Pengembalian</div><h3 class="fw-bold mb-0">{{ $totalPengembalian }}</h3><a href="{{ route('admin.pengembalian.index') }}" class="small text-decoration-none">Lihat transaksi</a></div></div><div class="col-6 col-xl-3"><div class="card p-3"><div class="eyebrow">Peminjaman</div><h3 class="fw-bold mb-0">{{ $peminjamanPending->count() + $peminjamanAktif->count() }}</h3><a href="{{ route('admin.peminjaman.index') }}" class="small text-decoration-none">Lihat transaksi</a></div></div></div>
  <div class="card p-3 mb-4"><div class="d-flex justify-content-between align-items-center mb-2"><h5 class="fw-bold mb-0">Pengajuan terbaru</h5><a href="{{ route('admin.peminjaman.index') }}" class="small text-decoration-none">Semua data</a></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Peminjam</th><th>Alat</th><th>Periode</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($peminjamanPending as $p)<tr><td>{{ $p->user->username ?? '-' }}</td><td>{{ $p->alat->nama_alat ?? '-' }}</td><td>{{ \Carbon\Carbon::parse($p->tgl_pinjam)->format('d M Y') }} - {{ \Carbon\Carbon::parse($p->tgl_harap_kembali)->format('d M Y') }}</td><td><span class="badge text-bg-warning">Pending</span></td><td class="text-end"><form method="POST" action="{{ route('peminjaman.setujui',$p->id) }}">@csrf<button class="btn btn-primary btn-sm">Setujui</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">Tidak ada pengajuan pending.</td></tr>@endforelse</tbody></table></div></div>
  <div class="row g-3 mb-4"><div class="col-sm-4"><div class="card p-3"><div class="stat-icon bg-primary-subtle text-primary mb-3"><i class="bi bi-box-seam"></i></div><div class="eyebrow">Total jenis alat</div><h3 class="fw-bold mb-0">{{ $alats->count() }}</h3></div></div><div class="col-sm-4"><div class="card p-3"><div class="stat-icon bg-success-subtle text-success mb-3"><i class="bi bi-check2-circle"></i></div><div class="eyebrow">Alat tersedia</div><h3 class="fw-bold mb-0">{{ $alats->where('status','ada')->count() }}</h3></div></div><div class="col-sm-4"><div class="card p-3"><div class="stat-icon bg-warning-subtle text-warning mb-3"><i class="bi bi-hourglass-split"></i></div><div class="eyebrow">Menunggu persetujuan</div><h3 class="fw-bold mb-0">{{ $peminjamanPending->count() }}</h3></div></div></div>
  <div class="card p-2 p-md-3"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>#</th><th>Nama alat</th><th>Kategori</th><th>Stok</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($alats as $i => $alat)<tr><td class="text-muted">{{ $i+1 }}</td><td class="fw-semibold">{{ $alat->nama_alat }}</td><td>{{ $alat->kategori->nama_kategori ?? '-' }}</td><td>{{ $alat->stok }}</td><td><span class="badge rounded-pill text-bg-{{ $alat->status === 'ada' ? 'success' : ($alat->status === 'rusak' ? 'danger' : 'secondary') }}">{{ str_replace('_',' ', ucfirst($alat->status)) }}</span></td><td class="text-end"><a href="{{ route('admin.alat.edit', $alat) }}" class="btn btn-sm btn-light text-primary me-1"><i class="bi bi-pencil"></i> Edit</a><form class="d-inline" method="POST" action="{{ route('admin.alat.destroy', $alat) }}" onsubmit="return confirm('Hapus alat ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-light text-danger"><i class="bi bi-trash"></i> Hapus</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada data alat.</td></tr>@endforelse</tbody></table></div></div>
@else
  <div class="mb-4"><div class="eyebrow">Panel petugas</div><h2 class="fw-bold mb-1">Operasional Peminjaman</h2><p class="text-muted">Tinjau pengajuan dan pantau alat yang sedang dipinjam.</p></div>
  <div class="row g-3 mb-4"><div class="col-md-6"><div class="card p-3"><div class="eyebrow">Menunggu persetujuan</div><h2 class="fw-bold">{{ $peminjamanPending->count() }}</h2><a href="#persetujuan" class="small text-decoration-none">Lihat pengajuan <i class="bi bi-arrow-right"></i></a></div></div><div class="col-md-6"><div class="card p-3"><div class="eyebrow">Peminjaman aktif</div><h2 class="fw-bold">{{ $peminjamanAktif->count() }}</h2><a href="#pengembalian" class="small text-decoration-none">Pantau pengembalian <i class="bi bi-arrow-right"></i></a></div></div></div>
  <div class="card p-3 mb-4" id="persetujuan"><h5 class="fw-bold">Pengajuan perlu ditinjau</h5><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Peminjam</th><th>Alat</th><th>Periode</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($peminjamanPending as $p)<tr><td>{{ $p->user->nama ?? $p->user->name ?? '-' }}</td><td>{{ $p->alat->nama_alat ?? '-' }}</td><td>{{ \Carbon\Carbon::parse($p->tgl_pinjam)->format('d M') }} - {{ \Carbon\Carbon::parse($p->tgl_harap_kembali)->format('d M Y') }}</td><td class="text-end"><form method="POST" action="{{ route('peminjaman.setujui',$p->id) }}">@csrf<button class="btn btn-primary btn-sm">Setujui</button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">Tidak ada pengajuan baru.</td></tr>@endforelse</tbody></table></div></div>
  <div class="card p-3" id="pengembalian"><h5 class="fw-bold">Peminjaman aktif</h5><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Peminjam</th><th>Alat</th><th>Rencana kembali</th><th>Status</th></tr></thead><tbody>@forelse($peminjamanAktif as $p)<tr><td>{{ $p->user->nama ?? $p->user->name ?? '-' }}</td><td>{{ $p->alat->nama_alat ?? '-' }}</td><td>{{ \Carbon\Carbon::parse($p->tgl_harap_kembali)->format('d M Y') }}</td><td><span class="badge text-bg-success">Dipinjam</span></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-3">Tidak ada alat yang sedang dipinjam.</td></tr>@endforelse</tbody></table></div></div>
@endif
@endsection
